
import { Provider, ServiceCategory, Booking, User, UserRole, ServiceItem } from './types';
import { getServiceImage } from './utils/images';

// Catalog of specific services for each category with Images
export const SERVICE_CATALOG: Record<ServiceCategory, ServiceItem[]> = {
  [ServiceCategory.ELECTRICIAN]: [
    { id: 'e1', name: 'Fan Repair & Installation', basePrice: 400, image: getServiceImage('Fan Repair & Installation') },
    { id: 'e2', name: 'Switch & Socket Fixing', basePrice: 200, image: getServiceImage('Switch & Socket Fixing') },
    { id: 'e3', name: 'Full House Wiring', basePrice: 5000, image: getServiceImage('Full House Wiring') },
    { id: 'e4', name: 'Light & Chandelier Installation', basePrice: 500, image: getServiceImage('Light & Chandelier Installation') },
    { id: 'e5', name: 'AC Power Point Fitting', basePrice: 800, image: getServiceImage('AC Power Point Fitting') },
    { id: 'e6', name: 'MCB & Fuse Repair', basePrice: 350, image: getServiceImage('MCB & Fuse Repair') },
    { id: 'e7', name: 'Inverter Installation', basePrice: 1200, image: getServiceImage('Inverter Installation') },
  ],
  [ServiceCategory.PLUMBER]: [
    { id: 'p1', name: 'Tap & Mixer Repair', basePrice: 150, image: getServiceImage('Tap & Mixer Repair') },
    { id: 'p2', name: 'Drain & Pipe Cleaning', basePrice: 350, image: getServiceImage('Drain & Pipe Cleaning') },
    { id: 'p3', name: 'Basin & Sink Installation', basePrice: 850, image: getServiceImage('Basin & Sink Installation') },
    { id: 'p4', name: 'Toilet & Flush Repair', basePrice: 450, image: getServiceImage('Toilet & Flush Repair') },
    { id: 'p5', name: 'Water Tank Cleaning', basePrice: 1000, image: getServiceImage('Water Tank Cleaning') },
    { id: 'p6', name: 'Shower Installation', basePrice: 600, image: getServiceImage('Shower Installation') },
    { id: 'p7', name: 'Pipe Leakage Fix', basePrice: 500, image: getServiceImage('Pipe Leakage Fix') },
  ],
  [ServiceCategory.CARPENTER]: [
    { id: 'c1', name: 'Furniture Assembly', basePrice: 600, image: getServiceImage('Furniture Assembly') },
    { id: 'c2', name: 'Door & Window Repair', basePrice: 400, image: getServiceImage('Door & Window Repair') },
    { id: 'c3', name: 'Custom Shelving & Cupboards', basePrice: 1500, image: getServiceImage('Custom Shelving & Cupboards') },
    { id: 'c4', name: 'Lock Installation', basePrice: 300, image: getServiceImage('Lock Installation') },
    { id: 'c5', name: 'Bed & Sofa Repair', basePrice: 500, image: getServiceImage('Bed & Sofa Repair') },
  ],
  [ServiceCategory.CLEANING]: [
    { id: 'cl1', name: 'Full Home Deep Clean', basePrice: 2500, image: getServiceImage('Full Home Deep Clean') },
    { id: 'cl2', name: 'Bathroom Deep Clean', basePrice: 500, image: getServiceImage('Bathroom Deep Clean') },
    { id: 'cl3', name: 'Kitchen Deep Clean', basePrice: 700, image: getServiceImage('Kitchen Deep Clean') },
    { id: 'cl4', name: 'Sofa & Carpet Cleaning', basePrice: 800, image: getServiceImage('Sofa & Carpet Cleaning') },
    { id: 'cl5', name: 'Balcony Cleaning', basePrice: 300, image: getServiceImage('Balcony Cleaning') },
  ],
  [ServiceCategory.HVAC]: [
    { id: 'h1', name: 'AC Service (Split/Window)', basePrice: 600, image: getServiceImage('AC Service (Split/Window)') },
    { id: 'h2', name: 'AC Gas Filling', basePrice: 1500, image: getServiceImage('AC Gas Filling') },
    { id: 'h3', name: 'AC Installation/Uninstallation', basePrice: 1200, image: getServiceImage('AC Installation/Uninstallation') },
    { id: 'h4', name: 'PCB Repair', basePrice: 2000, image: getServiceImage('PCB Repair') },
  ],
  [ServiceCategory.MOVING]: [
    { id: 'm1', name: 'House Shifting (1BHK)', basePrice: 3000, image: getServiceImage('House Shifting (1BHK)') },
    { id: 'm2', name: 'House Shifting (2-3BHK)', basePrice: 5500, image: getServiceImage('House Shifting (2-3BHK)') },
    { id: 'm3', name: 'Vehicle Transport', basePrice: 1500, image: getServiceImage('Vehicle Transport') },
  ],
  [ServiceCategory.GARDENING]: [
    { id: 'g1', name: 'Lawn Mowing', basePrice: 400, image: getServiceImage('Lawn Mowing') },
    { id: 'g2', name: 'Plant Trimming', basePrice: 300, image: getServiceImage('Plant Trimming') },
    { id: 'g3', name: 'Plant Potting', basePrice: 150, image: getServiceImage('Plant Potting') },
  ],
  [ServiceCategory.PAINTER]: [
    { id: 'pt1', name: 'Wall Painting', basePrice: 2000, image: getServiceImage('Wall Painting') },
    { id: 'pt2', name: 'Waterproofing', basePrice: 3500, image: getServiceImage('Waterproofing') },
    { id: 'pt3', name: 'Wood Polishing', basePrice: 1500, image: getServiceImage('Wood Polishing') },
  ],
  [ServiceCategory.PEST_CONTROL]: [
    { id: 'pc1', name: 'General Pest Control', basePrice: 900, image: getServiceImage('General Pest Control') },
    { id: 'pc2', name: 'Termite Treatment', basePrice: 3500, image: getServiceImage('Termite Treatment') },
    { id: 'pc3', name: 'Bed Bug Treatment', basePrice: 1500, image: getServiceImage('Bed Bug Treatment') },
  ],
  [ServiceCategory.APPLIANCE]: [
    { id: 'ap1', name: 'Washing Machine Repair', basePrice: 450, image: getServiceImage('Washing Machine Repair') },
    { id: 'ap2', name: 'Refrigerator Repair', basePrice: 500, image: getServiceImage('Refrigerator Repair') },
    { id: 'ap3', name: 'Microwave/Oven Repair', basePrice: 400, image: getServiceImage('Microwave/Oven Repair') },
  ]
};

const MOCK_AADHAAR_URL = "https://via.placeholder.com/300x200?text=Aadhaar+Card+Verified";

// Default availability for mock providers
const DEFAULT_AVAILABILITY = {
  days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
  startTime: '09:00',
  endTime: '18:00',
  blockedDates: []
};

// --- REALISTIC PROVIDERS FOR EVERY CATEGORY ---
export const MOCK_PROVIDERS: Provider[] = [
  // Demo Provider (Rajesh Kumar)
  {
    id: 'prov_rajesh',
    name: "Rajesh Kumar",
    category: ServiceCategory.ELECTRICIAN,
    rating: 4.9,
    reviewCount: 42,
    hourlyRate: 450,
    location: "Koramangala, Bangalore",
    distance: "0.8 km",
    imageUrl: getServiceImage('provider-rajesh'),
    aadhaarImageUrl: MOCK_AADHAAR_URL,
    description: "Experienced electrician with 10 years of experience. Quick troubleshooting and safe repairs.",
    skills: ["Wiring", "Switch Repair", "Fuse Box"],
    verified: true,
    reviews: [],
    status: 'approved',
    verificationStatus: 'verified',
    availability: DEFAULT_AVAILABILITY,
    walletBalance: 2500,
    totalEarned: 15000,
    totalWithdrawn: 12500,
    negativeBalanceLimit: 500,
    isNegativeActive: false,
    customPricing: {},
    performanceScore: 92,
    badge: 'Elite'
  },
  {
    id: 'prov_elec_1',
    name: "Volts & Sparks",
    category: ServiceCategory.ELECTRICIAN,
    rating: 4.8,
    reviewCount: 142,
    hourlyRate: 500,
    location: "Indiranagar, Bangalore",
    distance: "1.2 km",
    imageUrl: getServiceImage('provider-volts-sparks'),
    aadhaarImageUrl: MOCK_AADHAAR_URL,
    description: "Expert electrical services for residential and commercial properties. We handle everything from minor repairs to full house wiring.",
    skills: ["Wiring", "Fan Repair", "Switch Installation", "Inverters"],
    verified: true,
    reviews: [],
    status: 'approved',
    verificationStatus: 'verified',
    availability: DEFAULT_AVAILABILITY,
    walletBalance: 0,
    totalEarned: 0,
    totalWithdrawn: 0,
    negativeBalanceLimit: 500,
    isNegativeActive: false,
    customPricing: {},
    performanceScore: 88,
    badge: 'Top Rated'
  },
  {
    id: 'prov_plumb_1',
    name: "AquaFlow Plumbers",
    category: ServiceCategory.PLUMBER,
    rating: 4.9,
    reviewCount: 215,
    hourlyRate: 550,
    location: "Jayanagar, Bangalore",
    distance: "2.5 km",
    imageUrl: getServiceImage('provider-aquaflow'),
    aadhaarImageUrl: MOCK_AADHAAR_URL,
    description: "24/7 Emergency plumbing. Specialized in leak detection, pipe fitting, and bathroom installations.",
    skills: ["Leak Fix", "Taps", "Water Tanks", "Pipe Cleaning"],
    verified: true,
    reviews: [],
    status: 'approved',
    verificationStatus: 'verified',
    availability: DEFAULT_AVAILABILITY,
    walletBalance: 0,
    totalEarned: 0,
    totalWithdrawn: 0,
    negativeBalanceLimit: 500,
    isNegativeActive: false,
    customPricing: {},
    performanceScore: 91,
    badge: 'Elite'
  },
  {
    id: 'prov_carp_1',
    name: "WoodCraft Studios",
    category: ServiceCategory.CARPENTER,
    rating: 4.7,
    reviewCount: 88,
    hourlyRate: 600,
    location: "Whitefield, Bangalore",
    distance: "4.1 km",
    imageUrl: getServiceImage('provider-woodcraft'),
    aadhaarImageUrl: MOCK_AADHAAR_URL,
    description: "Master carpenters for custom furniture, repairs, and intricate woodwork. We bring your wood furniture back to life.",
    skills: ["Furniture Assembly", "Door Repair", "Cupboards", "Polishing"],
    verified: true,
    reviews: [],
    status: 'approved',
    verificationStatus: 'verified',
    availability: DEFAULT_AVAILABILITY,
    walletBalance: 0,
    totalEarned: 0,
    totalWithdrawn: 0,
    negativeBalanceLimit: 500,
    isNegativeActive: false,
    customPricing: {},
    performanceScore: 85,
    badge: 'Top Rated'
  },
  {
    id: 'prov_clean_1',
    name: "Sparkle Home Services",
    category: ServiceCategory.CLEANING,
    rating: 4.8,
    reviewCount: 310,
    hourlyRate: 350,
    location: "Koramangala, Bangalore",
    distance: "1.8 km",
    imageUrl: "",
    aadhaarImageUrl: MOCK_AADHAAR_URL,
    description: "Professional deep cleaning services. We use eco-friendly products safe for children and pets.",
    skills: ["Deep Clean", "Bathroom Cleaning", "Sofa Cleaning", "Kitchen Degreasing"],
    verified: true,
    reviews: [],
    status: 'approved',
    verificationStatus: 'verified',
    availability: DEFAULT_AVAILABILITY,
    walletBalance: 0,
    totalEarned: 0,
    totalWithdrawn: 0,
    negativeBalanceLimit: 500,
    isNegativeActive: false,
    customPricing: {},
    performanceScore: 89,
    badge: 'Top Rated'
  },
  {
    id: 'prov_hvac_1',
    name: "Cool Breeze ACs",
    category: ServiceCategory.HVAC,
    rating: 4.6,
    reviewCount: 95,
    hourlyRate: 700,
    location: "HSR Layout, Bangalore",
    distance: "3.2 km",
    imageUrl: "",
    aadhaarImageUrl: MOCK_AADHAAR_URL,
    description: "Certified AC technicians for all brands. Installation, repair, and annual maintenance contracts.",
    skills: ["AC Repair", "Gas Filling", "Installation", "Servicing"],
    verified: true,
    reviews: [],
    status: 'approved',
    verificationStatus: 'verified',
    availability: DEFAULT_AVAILABILITY,
    walletBalance: 0,
    totalEarned: 0,
    totalWithdrawn: 0,
    negativeBalanceLimit: 500,
    isNegativeActive: false,
    customPricing: {},
    performanceScore: 78,
    badge: 'Top Rated'
  },
  {
    id: 'prov_move_1',
    name: "Swift Shifters",
    category: ServiceCategory.MOVING,
    rating: 4.5,
    reviewCount: 150,
    hourlyRate: 1000,
    location: "Marathahalli, Bangalore",
    distance: "5.0 km",
    imageUrl: getServiceImage('provider-swift-shifters'),
    aadhaarImageUrl: MOCK_AADHAAR_URL,
    description: "Hassle-free house and office shifting. We handle packing, moving, and unpacking with care.",
    skills: ["House Shifting", "Packing", "Vehicle Transport"],
    verified: true,
    reviews: [],
    status: 'approved',
    verificationStatus: 'verified',
    availability: DEFAULT_AVAILABILITY,
    walletBalance: 0,
    totalEarned: 0,
    totalWithdrawn: 0,
    negativeBalanceLimit: 500,
    isNegativeActive: false,
    customPricing: {},
    performanceScore: 75,
    badge: 'Top Rated'
  },
  {
    id: 'prov_gard_1',
    name: "Green Thumb Gardens",
    category: ServiceCategory.GARDENING,
    rating: 4.9,
    reviewCount: 60,
    hourlyRate: 400,
    location: "Hebbal, Bangalore",
    distance: "6.5 km",
    imageUrl: getServiceImage('provider-green-thumb'),
    aadhaarImageUrl: MOCK_AADHAAR_URL,
    description: "Complete garden maintenance. Lawn mowing, pruning, potting, and landscape design.",
    skills: ["Lawn Mowing", "Pruning", "Potting", "Landscaping"],
    verified: false,
    reviews: [],
    status: 'approved',
    verificationStatus: 'verified',
    availability: DEFAULT_AVAILABILITY,
    walletBalance: 0,
    totalEarned: 0,
    totalWithdrawn: 0,
    negativeBalanceLimit: 500,
    isNegativeActive: false,
    customPricing: {},
    performanceScore: 93,
    badge: 'Elite'
  },
  {
    id: 'prov_paint_1',
    name: "Rainbow Painters",
    category: ServiceCategory.PAINTER,
    rating: 4.7,
    reviewCount: 75,
    hourlyRate: 0,
    location: "Banashankari, Bangalore",
    distance: "4.8 km",
    imageUrl: getServiceImage('provider-rainbow-painters'),
    aadhaarImageUrl: MOCK_AADHAAR_URL,
    description: "Professional wall painting, texture finishing, and waterproofing services.",
    skills: ["Wall Painting", "Waterproofing", "Texture Art", "Wood Polishing"],
    verified: true,
    reviews: [],
    status: 'approved',
    verificationStatus: 'verified',
    availability: DEFAULT_AVAILABILITY,
    walletBalance: 0,
    totalEarned: 0,
    totalWithdrawn: 0,
    negativeBalanceLimit: 500,
    isNegativeActive: false,
    customPricing: {},
    performanceScore: 82,
    badge: 'Top Rated'
  },
  {
    id: 'prov_pest_1',
    name: "PestGuard Solutions",
    category: ServiceCategory.PEST_CONTROL,
    rating: 4.8,
    reviewCount: 180,
    hourlyRate: 800,
    location: "JP Nagar, Bangalore",
    distance: "3.9 km",
    imageUrl: "",
    aadhaarImageUrl: MOCK_AADHAAR_URL,
    description: "Safe and odorless pest control. Specialized treatments for termites, cockroaches, and bed bugs.",
    skills: ["General Pest Control", "Termite Treatment", "Bed Bugs"],
    verified: true,
    reviews: [],
    status: 'approved',
    verificationStatus: 'verified',
    availability: DEFAULT_AVAILABILITY,
    walletBalance: 0,
    totalEarned: 0,
    totalWithdrawn: 0,
    negativeBalanceLimit: 500,
    isNegativeActive: false,
    customPricing: {},
    performanceScore: 87,
    badge: 'Top Rated'
  },
  {
    id: 'prov_app_1',
    name: "Appliance Fix Experts",
    category: ServiceCategory.APPLIANCE,
    rating: 4.6,
    reviewCount: 112,
    hourlyRate: 450,
    location: "Electronic City, Bangalore",
    distance: "8.0 km",
    imageUrl: getServiceImage('provider-appliance-fix'),
    aadhaarImageUrl: MOCK_AADHAAR_URL,
    description: "Repair services for washing machines, refrigerators, microwaves, and ovens. Original spare parts used.",
    skills: ["Washing Machine", "Refrigerator", "Microwave", "Oven"],
    verified: true,
    reviews: [],
    status: 'approved',
    verificationStatus: 'verified',
    availability: DEFAULT_AVAILABILITY,
    walletBalance: 0,
    totalEarned: 0,
    totalWithdrawn: 0,
    negativeBalanceLimit: 500,
    isNegativeActive: false,
    customPricing: {},
    performanceScore: 79,
    badge: 'Top Rated'
  }
];

export const MOCK_USER: User = {
  id: 'u1',
  name: 'Amit Patel',
  username: 'amitp',
  email: 'amit@example.com',
  phone: '+91 9876543210',
  role: UserRole.CUSTOMER,
  addresses: [
    { id: 'a1', label: 'Home', fullAddress: 'Flat 402, Sunshine Apts, Indiranagar, Bangalore', isPrimary: true },
    { id: 'a2', label: 'Office', fullAddress: 'Tech Park, Whitefield, Bangalore', isPrimary: false }
  ]
};

const providerUsers: User[] = MOCK_PROVIDERS.map(p => ({
  id: p.id,
  name: p.name,
  username: p.name.replace(/\s+/g, '').toLowerCase(),
  email: `contact@${p.name.replace(/\s+/g, '').toLowerCase()}.com`,
  phone: '9876500000',
  role: UserRole.PROVIDER,
  addresses: [],
  providerProfileId: p.id
}));

export const MOCK_USERS: User[] = [MOCK_USER, ...providerUsers];

export const MOCK_BOOKINGS: Booking[] = [
  {
    id: 'b1',
    providerId: 'prov_elec_1',
    customerId: 'u1',
    customerName: 'Amit Patel',
    providerName: "Volts & Sparks",
    serviceDate: '2023-11-15T14:00:00',
    bookingTime: '14:00',
    timeSlot: '12-4',
    status: 'PAID',
    bookingQueueType: 'standard',
    category: ServiceCategory.ELECTRICIAN,
    serviceType: "Fan Repair & Installation",
    description: "Living room ceiling fan installation",
    address: "Flat 402, Sunshine Apts, Indiranagar",
    billing: {
      subtotal: 400,
      tax: 72,
      platformFee: 20,
      total: 492,
      paymentMethod: 'ONLINE',
      transactionId: 'TXN123456',
      paidAt: '2023-11-15T15:30:00'
    },
    review: {
       id: 'rev_old_1',
       author: 'Amit Patel',
       rating: 5,
       text: "Quick and clean work.",
       date: '2023-11-15',
       verifiedBooking: true
    },
    createdAt: '2023-11-14T10:00:00'
  },
  {
    id: 'b_recent_1',
    providerId: 'prov_clean_1',
    customerId: 'u1',
    customerName: 'Amit Patel',
    providerName: "Sparkle Home Services",
    serviceDate: new Date(Date.now() + 86400000).toISOString(), 
    bookingTime: '09:00',
    timeSlot: '8-12',
    status: 'PENDING',
    bookingQueueType: 'standard',
    category: ServiceCategory.CLEANING,
    serviceType: "Full Home Deep Clean",
    description: "Urgent cleaning required.",
    address: "Flat 402, Sunshine Apts, Indiranagar",
    billing: {
      subtotal: 2500,
      tax: 450,
      platformFee: 20,
      total: 2970
    },
    createdAt: new Date().toISOString()
  },
  {
    id: 'b_rajesh_1',
    providerId: 'prov_rajesh',
    customerId: 'u1',
    customerName: 'Amit Patel',
    providerName: "Rajesh Kumar",
    serviceDate: new Date(Date.now() + 172800000).toISOString(),
    bookingTime: '11:00',
    timeSlot: '8-12',
    status: 'PENDING',
    bookingQueueType: 'standard',
    category: ServiceCategory.ELECTRICIAN,
    serviceType: "Switch & Socket Fixing",
    description: "Main switchboard is heating up.",
    address: "Flat 402, Sunshine Apts, Indiranagar",
    billing: {
      subtotal: 200,
      tax: 36,
      platformFee: 20,
      total: 256
    },
    createdAt: new Date().toISOString()
  }
];
